begin;

alter table if exists public.leads
  add column if not exists last_classification_at timestamptz,
  add column if not exists last_status_changed_at timestamptz;

create table if not exists public.integration_events (
  event_id text primary key,
  lead_id bigint references public.leads(id) on delete cascade,
  event_type text not null,
  event_version integer not null default 1,
  source text not null,
  occurred_at timestamptz not null,
  payload jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists integration_events_lead_occurred_at_idx
  on public.integration_events(lead_id, occurred_at desc);

create index if not exists integration_events_type_occurred_at_idx
  on public.integration_events(event_type, occurred_at desc);

create table if not exists public.lead_status_events (
  id bigint generated by default as identity primary key,
  lead_id bigint not null references public.leads(id) on delete cascade,
  source_event_id text unique references public.integration_events(event_id) on delete set null,
  source text not null,
  from_status text,
  to_status text not null,
  reason_code text not null,
  reason_text text,
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists lead_status_events_lead_occurred_at_idx
  on public.lead_status_events(lead_id, occurred_at desc);

create table if not exists public.lead_handoffs (
  id bigint generated by default as identity primary key,
  lead_id bigint not null references public.leads(id) on delete cascade,
  summary_context text not null,
  priority text not null default 'normal',
  requested_by text not null default 'ai',
  source_event_id text unique,
  created_at timestamptz not null default now()
);

alter table if exists public.lead_handoffs
  add column if not exists priority text not null default 'normal',
  add column if not exists requested_by text not null default 'ai',
  add column if not exists source_event_id text;

create index if not exists lead_handoffs_lead_created_at_idx
  on public.lead_handoffs(lead_id, created_at desc);

create unique index if not exists lead_handoffs_source_event_id_idx
  on public.lead_handoffs(source_event_id)
  where source_event_id is not null;

alter table public.integration_events enable row level security;
alter table public.lead_status_events enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'integration_events'
      and policyname = 'Users can view their own integration events'
  ) then
    create policy "Users can view their own integration events"
      on public.integration_events
      for select
      using (
        exists (
          select 1
          from public.leads
          where leads.id = integration_events.lead_id
            and leads.user_id = auth.uid()
        )
      );
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'integration_events'
      and policyname = 'Users can insert their own integration events'
  ) then
    create policy "Users can insert their own integration events"
      on public.integration_events
      for insert
      with check (
        exists (
          select 1
          from public.leads
          where leads.id = integration_events.lead_id
            and leads.user_id = auth.uid()
        )
      );
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'lead_status_events'
      and policyname = 'Users can view their own lead status events'
  ) then
    create policy "Users can view their own lead status events"
      on public.lead_status_events
      for select
      using (
        exists (
          select 1
          from public.leads
          where leads.id = lead_status_events.lead_id
            and leads.user_id = auth.uid()
        )
      );
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'lead_status_events'
      and policyname = 'Users can insert their own lead status events'
  ) then
    create policy "Users can insert their own lead status events"
      on public.lead_status_events
      for insert
      with check (
        exists (
          select 1
          from public.leads
          where leads.id = lead_status_events.lead_id
            and leads.user_id = auth.uid()
        )
      );
  end if;
end $$;

commit;
