begin;

alter table if exists public.leads
  add column if not exists external_session_id text,
  add column if not exists score_total integer,
  add column if not exists lead_tier text,
  add column if not exists qualification_summary text,
  add column if not exists last_message_at timestamptz,
  add column if not exists last_message_preview text;

alter table if exists public.messages
  add column if not exists message_direction text,
  add column if not exists content_type text,
  add column if not exists external_message_id text,
  add column if not exists metadata jsonb not null default '{}'::jsonb;

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  lead_id bigint references public.leads(id) on delete cascade,
  type text not null,
  title text not null,
  body text,
  is_read boolean not null default false,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists leads_user_phone_idx on public.leads(user_id, phone_number);
create index if not exists leads_external_session_idx on public.leads(external_session_id);
create index if not exists leads_last_message_at_idx on public.leads(last_message_at desc nulls last);
create index if not exists messages_lead_created_at_idx on public.messages(lead_id, created_at desc);
create index if not exists messages_external_message_id_idx on public.messages(external_message_id);
create index if not exists notifications_user_created_at_idx on public.notifications(user_id, created_at desc);
create index if not exists notifications_lead_idx on public.notifications(lead_id);

commit;
